// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDSl26XrgTIzwqFYUX2UXDg5VvWsSPX5E',
    appId: '1:1056643711862:web:a3f8e657fa250bbae03057',
    messagingSenderId: '1056643711862',
    projectId: 'pemetaan-pohon-11417',
    authDomain: 'pemetaan-pohon-11417.firebaseapp.com',
    storageBucket: 'pemetaan-pohon-11417.firebasestorage.app',
    measurementId: 'G-S7WDFS1EXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB75WAdKhHhR15wiOe73_w0mCEkwUT600I',
    appId: '1:1056643711862:android:1b8b4bf9f66e4edae03057',
    messagingSenderId: '1056643711862',
    projectId: 'pemetaan-pohon-11417',
    storageBucket: 'pemetaan-pohon-11417.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYK6xku0KXfbhqGVtS5EOENDdwpjxLpI',
    appId: '1:1056643711862:ios:d904a99371dab4a7e03057',
    messagingSenderId: '1056643711862',
    projectId: 'pemetaan-pohon-11417',
    storageBucket: 'pemetaan-pohon-11417.firebasestorage.app',
    iosBundleId: 'com.example.pemetaanPohon',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWYK6xku0KXfbhqGVtS5EOENDdwpjxLpI',
    appId: '1:1056643711862:ios:d904a99371dab4a7e03057',
    messagingSenderId: '1056643711862',
    projectId: 'pemetaan-pohon-11417',
    storageBucket: 'pemetaan-pohon-11417.firebasestorage.app',
    iosBundleId: 'com.example.pemetaanPohon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDSl26XrgTIzwqFYUX2UXDg5VvWsSPX5E',
    appId: '1:1056643711862:web:b33583604dacc1f3e03057',
    messagingSenderId: '1056643711862',
    projectId: 'pemetaan-pohon-11417',
    authDomain: 'pemetaan-pohon-11417.firebaseapp.com',
    storageBucket: 'pemetaan-pohon-11417.firebasestorage.app',
    measurementId: 'G-3YZX6JDCVV',
  );
}
